service: sls-lambda-dynamodb

frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  profile: serverlessUser
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    tableName: ${self:custom.tableName}
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'

custom:
  customDomain:
    domainName: api.gluzman.net
    basePath: ''
    certificateName: '*.gluzman.net'
    stage: ${self:provider.stage}
    createRoute53: true
    createRoute53IPv6Record: false
    endpointType: regional
    apiType: http

  tableName: player-points
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

functions: ${file(yml/functions.yml)}

resources:
  - ${file(yml/dynamodb.yml)}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager
