service: sls-lambda-dynamodb

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: serverlessUser
  stage: dev
  environment:
    tableName: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'

custom:
  tableName: player-points
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions: ${file(yml/functions.yml)}

resources:
  - ${file(yml/dynamodb.yml)}
