@url = https://r9u8jnwzx6.execute-api.us-east-1.amazonaws.com/dev
@url_custom_domain = api.gluzman.net
@url_localhost = http://[::1]:3000
###
GET {{url}}/player-score

###
GET {{url}}/player-score/aa

###
POST {{url}}/player-score
Content-Type: application/json

{
    "name": "Idan",
    "score": 20,
    "game": "football"
}

###
PATCH {{url}}/player-score/2b90f3d9-20d4-44e8-b71e-6eadf6e044cd
Content-Type: application/json

{
    "score": 44
}


###
DELETE {{url}}/player-score/3e32fe18-1a6a-4542-89ad-0f6a48a387b2

###
GET {{url}}/game-scores/tennis

###
GET {{url_localhost}}/player-score 

###
POST {{url_localhost}}/player-score
Content-Type: application/json

{
    "name": "Idan",
    "score": 20,
    "game": "football"
}