@url = https://r9u8jnwzx6.execute-api.us-east-1.amazonaws.com/dev
@url_custom_domain = api.gluzman.net
@url_localhost = http://[::1]:3000
###
GET {{url}}/player-score

###
GET {{url}}/player-score/c95b7d42-be1a-48f3-aedd-85f2f63a87c1

###
POST {{url}}/player-score
Content-Type: application/json

{
    "name": "Nir",
    "score": 14,
    "game": "swimming"
}

###
PATCH {{url}}/player-score/c95b7d42-be1a-48f3-aedd-85f2f63a87c1
Content-Type: application/json

{
    "score": 44
}


###
DELETE {{url}}/player-score/c95b7d42-be1a-48f3-aedd-85f2f63a87c1

###
GET {{url}}/game-scores/tennis

###
GET {{url_localhost}}/player-score 

###
POST {{url_localhost}}/player-score
Content-Type: application/json

{
    "name": "Idan",
    "score": 20,
    "game": "football"
}